### ISSUE TITLE
UI Issues / Todo

### ISSUE THREAD

**Issue by varmichelle** [EVSD/EVSD-SITE#50]
- [ ] footer floating (space between bottom of footer and bottom of page / right of page)
- [ ] radio buttons not working
- [ ] navbar dropdown not working
- [ ] button UI
- [ ] input for some areas (account balance logging, payment buttons, etc)
- [ ] homepage content + UI

**Comment by aeolyus** [comment]
Look at 1.0
